version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: local_user
      MONGO_INITDB_ROOT_PASSWORD: local
    volumes:
      - ./mongodb_data:/data/db

volumes:
  mongodb_data: